replicaCount: 1

image:
  repository: orgam/NBA-statistics
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
